### ISSUE TITLE
DatabaseConnector::insertTable fails for Redshift

### ISSUE THREAD

**Issue by pavgra** [OHDSI/DatabaseConnector#102] opened 2019-09-14 00:05 UTC
The following code
```
a <- c('a', 'b')
b <- c(as.POSIXct(strptime("2011-03-27 01:30:00", "%Y-%m-%d %H:%M:%S")), as.POSIXct(strptime("2010-10-31 01:30:00", "%Y-%m-%d %H:%M:%S")))
table <- data.frame(a, b)

DatabaseConnector::insertTable(connection = rsConn,
                               tableName = "#random",
                               data = table,
                               dropTableIfExists = TRUE,
                               createTable = TRUE,
                               tempTable = TRUE,
                               oracleTempSchema = oracleTempSchema)
```

produces the next SQL statement

```
CREATE TEMP TABLE #jcpnljtzqrrpjlzeswjjnapj (a,b )  AS SELECT CAST('a' AS VARCHAR(255)),CAST('2011-03-27 01:30:00' AS DATETIME2)
UNION ALL
SELECT 'b','2010-10-31 01:30:00'
```

which fails in Redshift
```
[42704][500310] [Amazon](500310) Invalid operation: type "datetime2" does not exist;
java.lang.RuntimeException: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: type "datetime2" does not exist;
```

**Comment by pavgra** [comment] 2019-09-17 12:01
Fixed by https://github.com/OHDSI/DatabaseConnector/commit/ba1ce9f6503abc39de94a1ba250d12651b4697ce

**Comment by pavgra** [comment] 2019-09-18 14:49
Seems that Redshift requires explicit type casts same as BQ:
```
DBMS:
redshift

Error:
java.sql.SQLException: [Amazon](500310) Invalid operation: UNION types integer and character varying cannot be matched;

SQL:
CREATE TABLE #xupxrcuesawblrhhdmlr DISTSTYLE ALL
AS
WITH data (exposure_id,outcome_id)
AS (SELECT CAST('9' AS INTEGER),CAST('437643' AS INTEGER)
UNION ALL
SELECT CAST('9' as TEXT) ,'260139'
UNION ALL
SELECT '9','257007'
```

**Comment by schuemie** [comment] 2019-09-19 00:12
This is caused by the issue discussed [here](https://github.com/OHDSI/SqlRender/issues/192).

I dropped this rule for RedShift in the develop version, so if you get that one (as required in the DESCRIPTION of the DatabaseConnector develop version) this problem should be fixed.

**Closed** 2021-04-19 09:11 UTC
